services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feathers_and_fairways
    ports:
      - "41549:41549"
    env_file: ".env"
    volumes:
      - ./data:/app/data
      - ./dist:/app/dist
    restart: unless-stopped
